-- Run this in Supabase > SQL Editor.
-- It is safe to run on a fresh project or on an existing Wedding Adventure table.
-- Player names are treated as unique case-insensitively and only each player's
-- highest score is retained. If scores tie, the faster completion time wins.

create table if not exists public.wedding_scores (
  id bigint generated by default as identity primary key,
  player_name text not null check (char_length(player_name) between 1 and 20),
  player_key text,
  score integer not null check (score >= 0 and score <= 1000000),
  time_seconds numeric(8,2) not null check (time_seconds >= 0 and time_seconds <= 10000),
  rings integer not null default 0 check (rings >= 0 and rings <= 1000),
  hearts integer not null default 0 check (hearts >= 0 and hearts <= 1000),
  created_at timestamptz not null default now()
);

alter table public.wedding_scores
  add column if not exists player_key text;

-- Normalise existing rows so "Alex", "alex" and " ALEX " are the same player.
update public.wedding_scores
set player_key = lower(regexp_replace(trim(player_name), '\\s+', ' ', 'g'))
where player_key is null or player_key = '';

-- Remove older/lower duplicate scores before adding the unique constraint.
-- Highest score wins; for a tied score, fastest time wins.
with ranked as (
  select id,
         row_number() over (
           partition by player_key
           order by score desc, time_seconds asc, created_at asc, id asc
         ) as rn
  from public.wedding_scores
)
delete from public.wedding_scores w
using ranked r
where w.id = r.id and r.rn > 1;

alter table public.wedding_scores
  alter column player_key set not null;

create unique index if not exists wedding_scores_player_key_uidx
  on public.wedding_scores (player_key);

create index if not exists wedding_scores_score_idx
  on public.wedding_scores (score desc, time_seconds asc);

alter table public.wedding_scores enable row level security;

drop policy if exists "Public can read wedding leaderboard" on public.wedding_scores;
create policy "Public can read wedding leaderboard"
on public.wedding_scores
for select
to anon
using (true);

-- Direct inserts/updates are not needed; clients submit through the RPC below.
drop policy if exists "Public can submit wedding scores" on public.wedding_scores;
drop policy if exists "Public can update wedding scores" on public.wedding_scores;

create or replace function public.submit_wedding_score(
  p_player_name text,
  p_player_key text,
  p_score integer,
  p_time_seconds numeric,
  p_rings integer,
  p_hearts integer
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if char_length(p_player_name) not between 1 and 20
     or char_length(p_player_key) not between 1 and 20
     or p_score not between 0 and 1000000
     or p_time_seconds not between 0 and 10000
     or p_rings not between 0 and 1000
     or p_hearts not between 0 and 1000 then
    raise exception 'Invalid score submission';
  end if;

  insert into public.wedding_scores (
    player_name, player_key, score, time_seconds, rings, hearts, created_at
  ) values (
    trim(regexp_replace(p_player_name, '\\s+', ' ', 'g')),
    lower(trim(regexp_replace(p_player_key, '\\s+', ' ', 'g'))),
    p_score,
    p_time_seconds,
    p_rings,
    p_hearts,
    now()
  )
  on conflict (player_key) do update
  set player_name = excluded.player_name,
      score = excluded.score,
      time_seconds = excluded.time_seconds,
      rings = excluded.rings,
      hearts = excluded.hearts,
      created_at = now()
  where excluded.score > wedding_scores.score
     or (excluded.score = wedding_scores.score
         and excluded.time_seconds < wedding_scores.time_seconds);
end;
$$;

revoke all on function public.submit_wedding_score(text,text,integer,numeric,integer,integer) from public;
grant execute on function public.submit_wedding_score(text,text,integer,numeric,integer,integer) to anon;
